version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    target-branch: "development"
    
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    target-branch: "development"
