version: '3'

services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/panaceum-server/src
    command: npm build

  client:
    build: ./client
    expose:
      - ${APP_CLIENT_PORT}
    environment:
      APP_CLIENT_PORT: ${APP_CLIENT_PORT}
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./client/src:/srv/app/panaceum-client/src
      - ./client/assets:/srv/app/panaceum-client/assets
    links:
      - server
    command: npm run build