# This workflow will apply Prettier to the following files in '/src' exclusively: 
# JavaScript, Typescript, JavaScript-React, TypeScript-React, CSS & SCSS Stylesheets

name: Continuous Integration

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify Code Action
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --config ./.prettierrc --ignore-path ./.prettierignore --write **/src/**/*.{js,jsx,ts,tsx,css,scss}
          commit_message: "Prettier Format GitHub Action"